version: "3.7"

networks:
  frontend:

services:
  railsapp:
    image: railsapp:1.0
    networks:
      - frontend
    build: ./railsapp
    ports:
      - 8011:9000
  
  guacamole:
    image: guacamole:1.0
    networks:
      - frontend
    build: ./guacamole
    ports:
      - 8081:8080